/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HistorialRouteImport } from './routes/historial'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JornadaNuevaRouteImport } from './routes/jornada.nueva'
import { Route as JornadaIdRouteImport } from './routes/jornada.$id'

const HistorialRoute = HistorialRouteImport.update({
  id: '/historial',
  path: '/historial',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JornadaNuevaRoute = JornadaNuevaRouteImport.update({
  id: '/jornada/nueva',
  path: '/jornada/nueva',
  getParentRoute: () => rootRouteImport,
} as any)
const JornadaIdRoute = JornadaIdRouteImport.update({
  id: '/jornada/$id',
  path: '/jornada/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/historial': typeof HistorialRoute
  '/jornada/$id': typeof JornadaIdRoute
  '/jornada/nueva': typeof JornadaNuevaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/historial': typeof HistorialRoute
  '/jornada/$id': typeof JornadaIdRoute
  '/jornada/nueva': typeof JornadaNuevaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/historial': typeof HistorialRoute
  '/jornada/$id': typeof JornadaIdRoute
  '/jornada/nueva': typeof JornadaNuevaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/historial' | '/jornada/$id' | '/jornada/nueva'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/historial' | '/jornada/$id' | '/jornada/nueva'
  id: '__root__' | '/' | '/historial' | '/jornada/$id' | '/jornada/nueva'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HistorialRoute: typeof HistorialRoute
  JornadaIdRoute: typeof JornadaIdRoute
  JornadaNuevaRoute: typeof JornadaNuevaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/historial': {
      id: '/historial'
      path: '/historial'
      fullPath: '/historial'
      preLoaderRoute: typeof HistorialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jornada/nueva': {
      id: '/jornada/nueva'
      path: '/jornada/nueva'
      fullPath: '/jornada/nueva'
      preLoaderRoute: typeof JornadaNuevaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jornada/$id': {
      id: '/jornada/$id'
      path: '/jornada/$id'
      fullPath: '/jornada/$id'
      preLoaderRoute: typeof JornadaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HistorialRoute: HistorialRoute,
  JornadaIdRoute: JornadaIdRoute,
  JornadaNuevaRoute: JornadaNuevaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
